# Generated by Django 4.0 on 2021-12-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyapp', '0002_course_image_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='pyapp.Tag'),
        ),
    ]
